--------------------------------------------------------------------------------
Configuration
--------------------------------------------------------------------------------
host
 trace A (shutdown_block_recv.strace.client.linux)
 trace B (shutdown_block_recv.strace.server.linux)

--------------------------------------------------------------------------------
Verifying Traces
--------------------------------------------------------------------------------
TCP socket A0 connecting to socket B0 (public address 127.0.0.1:12345)
TCP server socket B0 (private address 127.0.0.1:12345) returning socket B1, which is connected to socket A0 (public address 127.0.0.1:59187)
[Warning] TCP socket A0 is being used for network operations by multiple threads
[Warning] TCP socket A0 was closed by a different thread than the one using it for network operations

Done

--------------------------------------------------------------------------------
TCP Connection Statistics
--------------------------------------------------------------------------------
Connection from socket A0 (public address 127.0.0.1:59187) to socket B1 (public address 127.0.0.1:12345)
 * Data sent to accepting socket B1: 0 bytes sent, 0 bytes received, 0 bytes lost
 * Data sent to connected socket A0: 5 bytes sent, 0 bytes received, 5 bytes lost (100.00%)
 * [Possible Application Misbehavior] Data loss is most likely due to application behavior

--------------------------------------------------------------------------------
Possible Problems Detected
--------------------------------------------------------------------------------
 * [Possible Application Misbehavior] Trace A has 1 TCP connection(s) to 127.0.0.1:12345 with data left in the buffers

For more details, adjust the variables defined in trace_output.py and posix_output.py to change the level of output
